services:
    oro_infinite_pay.integation.infinite_pay.channel:
        class: 'Oro\Bundle\InfinitePayBundle\Integration\InfinitePayChannelType'
        tags:
            - { name: oro_integration.channel, type: infinite_pay }

    oro_infinite_pay.integration.infinite_pay.transport:
        class: 'Oro\Bundle\InfinitePayBundle\Integration\InfinitePayTransport'
        tags:
            - { name: oro_integration.transport, type: infinite_pay, channel_type: infinite_pay }

    oro_infinite_pay.client.factory:
        class: 'Oro\Bundle\InfinitePayBundle\Service\InfinitePay\Factory\InfinitePayClientFactory'
        public: false
        arguments:
            - '@oro_infinite_pay.soap_client_logger'

    oro_infinite_pay.soap_client_logger:
        class: 'Oro\Bundle\InfinitePayBundle\Service\InfinitePay\Logger\InfinitePayAPILogger'
        arguments:
            - '@logger'

    oro_infinite_pay.soap.gateway:
        class: 'Oro\Bundle\InfinitePayBundle\Gateway\SoapGateway'
        arguments:
            - '@oro_infinite_pay.client.factory'

    oro_infinite_pay.method.provider.invoice_number_generator:
        class: 'Oro\Bundle\InfinitePayBundle\Method\Provider\InvoiceNumberGenerator'

    oro_infinite_pay.property_accessor.customer:
        class: 'Oro\Bundle\InfinitePayBundle\Action\PropertyAccessor\CustomerPropertyAccessor'
        arguments:
            - '@property_accessor'

    oro_infinite_pay.validator.customer_require_vat_id:
        class: 'Oro\Bundle\InfinitePayBundle\Validator\Constraints\CustomerRequireVatIdValidator'
        calls:
            - [setFrontendHelper, ['@oro_frontend.request.frontend_helper']]
        tags:
            - { name: validator.constraint_validator, alias: oro_infinite_pay_customer_require_vat_id_validator }

    Oro\Bundle\InfinitePayBundle\Entity\Repository\InfinitePaySettingsRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'Oro\Bundle\InfinitePayBundle\Entity\InfinitePaySettings'
        calls:
            - [ setAclHelper, [ '@oro_security.acl_helper' ] ]
        tags:
            - { name: doctrine.repository_service }
