Oro\Bundle\CustomerBundle\Entity\CustomerAddress:
    properties:
        frontendOwner:
            - Oro\Bundle\InfinitePayBundle\Validator\Constraints\CustomerRequireVatId: ~

Oro\Bundle\InfinitePayBundle\Entity\InfinitePaySettings:
    properties:
        infinitePayLabels:
            - NotBlank: ~
        infinitePayShortLabels:
            - NotBlank: ~
        infinitePayClientRef:
            - NotBlank: ~
            - Length:
                max: 255
        infinitePayUsername:
            - NotBlank: ~
            - Length:
                max: 255
        infinitePayPassword:
            - NotBlank: ~
            - Length:
                max: 255
        infinitePaySecret:
            - NotBlank: ~
            - Length:
                max: 255
